/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi_kasir_nabila;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;
import java.util.Locale;


/**
 *
 * @author RPL-PC
 */
public class Form_Produk extends javax.swing.JFrame {
    Connection con;
    DefaultTableModel tm;
    String filename=null;
    
     private void connect(){
        con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/db_kasir_nabila", "root", "");
        } catch(Exception e) {
            System.out.print("ERROR KONEKSI KE DATABASE:\n" + e);
        }
}
     
     private void ambilData(){
     try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM tbl_satuan");
            ResultSet r = s.executeQuery();
            while (r.next()) {                
                cbsat.addItem(r.getString("nama_satuan"));
            }
            
            PreparedStatement sm = con.prepareStatement("SELECT * FROM tbl_kategori");
            ResultSet rm = sm.executeQuery();
            while (rm.next()) {                
                cbkat.addItem(rm.getString("nama_kategori"));
            }
        }catch(Exception e){
            
        }
}
     
     private void refreshTable(){
        tm = new DefaultTableModel(
            null,
            new Object[] {"Kode Produk","Nama Produk","Harga Jual","Harga Beli","Stok","Satuan","Kategori"}
        );
        tbl_datapro.setModel(tm);
        tm.getDataVector().removeAllElements();
        try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM tbl_produk");
            ResultSet r = s.executeQuery();
            while(r.next()) {
                Object[] data = {
                 r.getString(1),
                 r.getString(2),
                 r.getString(3),
                 r.getString(4),
                 r.getString(5),
                 r.getString(6),
                 r.getString(7)
                };
                tm.addRow(data);
            }
        } catch(Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
}

    
    // Metode lain dari kelas Barang    

    /**
     * Creates new form Pendataan_barang
     */
    
    public Form_Produk() {
        initComponents();
        connect();
        ambilData();
        refreshTable();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtkode_pro = new javax.swing.JTextField();
        txtnm_pro = new javax.swing.JTextField();
        txtharga_jual = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_datapro = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtstok = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtharga_beli = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbsat = new javax.swing.JComboBox<>();
        cbkat = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-accessories-58.png"))); // NOI18N
        jLabel6.setText("PRODUK");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Kode Produk");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Nama Produk");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Harga Jual");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        jPanel2.add(txtkode_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 150, -1));
        jPanel2.add(txtnm_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 150, -1));
        jPanel2.add(txtharga_jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 150, -1));

        tbl_datapro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbl_datapro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Produk", "Nama Produk", "Harga Jual", "Harga Beli", "Stok", "Satuan", "Kategori"
            }
        ));
        tbl_datapro.setGridColor(new java.awt.Color(255, 153, 204));
        tbl_datapro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dataproMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_datapro);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 870, 510));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Stok");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));
        jPanel2.add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 150, -1));

        save.setBackground(new java.awt.Color(255, 153, 204));
        save.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add.png"))); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        edit.setBackground(new java.awt.Color(255, 153, 204));
        edit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit.png"))); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel2.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, -1, -1));

        delete.setBackground(new java.awt.Color(255, 153, 204));
        delete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete.png"))); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, -1, -1));

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        jPanel2.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 150, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Harga Beli");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        jPanel2.add(txtharga_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 150, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Satuan");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Kategori");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-search-32.png"))); // NOI18N
        jButton1.setText("CARI");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        jPanel2.add(cbsat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 150, -1));

        jPanel2.add(cbkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1305, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
         // TODO add your handling code here:
         try {
    // Mengecek apakah barang dengan kode atau nama yang sama sudah ada dalam database
    String query = "SELECT * FROM tbl_produk WHERE kode_produk = ? OR nama_produk = ?";
    PreparedStatement psCheck = con.prepareStatement(query);
    psCheck.setString(1, txtkode_pro.getText());
    psCheck.setString(2, txtnm_pro.getText());
    ResultSet rs = psCheck.executeQuery();
    
    if (rs.next()) {
        // Jika barang sudah ada dalam database, tampilkan pesan kesalahan
        JOptionPane.showMessageDialog(this, "Barang dengan kode atau nama yang sama sudah ada dalam database.");
    } else {
        // Jika barang belum ada dalam database, lakukan operasi INSERT
        PreparedStatement ps = con.prepareStatement("INSERT INTO tbl_produk VALUES (?,?,?,?,?,?,?)");
        ps.setString(1, txtkode_pro.getText());
        ps.setString(2, txtnm_pro.getText());
        ps.setString(5, txtharga_jual.getText());
        ps.setString(6, txtharga_beli.getText());
        ps.setString(7, txtstok.getText());
        ps.setString(3, cbsat.getSelectedItem().toString());
        ps.setString(4, cbkat.getSelectedItem().toString());
        
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data telah tersimpan");
        
        refreshTable();
    }
} catch(Exception e){
    System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
}

    }//GEN-LAST:event_saveActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement ps = con.prepareStatement("UPDATE tbl_produk SET  nama_produk=?, harga_jual=?, harga_beli=?, stok=?, nama_satuan=?, nama_kategori=? WHERE kode_produk=?");
            ps.setString(1, txtnm_pro.getText());
            ps.setString(2, txtharga_jual.getText());
            ps.setString(3, txtharga_beli.getText());
            ps.setString(4, txtstok.getText());
            ps.setString(5, cbsat.getSelectedItem().toString());
            ps.setString(6, cbkat.getSelectedItem().toString());
            ps.setString(7, txtkode_pro.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Telah Terupdate");
            refreshTable();
            txtnm_pro.setText("");
            txtharga_jual.setText("");
            txtharga_beli.setText("");
            txtstok.setText("");
            txtkode_pro.setText("");
        } catch(Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Anda Yakin Ingin Menghapus Data Ini='"+txtkode_pro.getText()+"'",".:: Konfirmasi ::.", JOptionPane.YES_NO_OPTION);
            if (ok==0){
                try {
            PreparedStatement ps = con.prepareStatement("DELETE FROM tbl_produk WHERE kode_produk=?");
            ps.setString(1, txtkode_pro.getText());
            ps.executeUpdate();
            refreshTable();
            txtkode_pro.setText("");
            txtnm_pro.setText("");
            txtharga_jual.setText("");
            txtharga_beli.setText("");
            txtstok.setText("");
        } catch(Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
            }
    }//GEN-LAST:event_deleteActionPerformed

    private void tbl_dataproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataproMouseClicked
        // TODO add your handling code here:
        int i = tbl_datapro.getSelectedRow();
        if (i == -1) {
            return;
        }
        String kode_produk = (String) tm.getValueAt (i, 0);
        txtkode_pro.setText(kode_produk);
        String nama_produk = (String) tm.getValueAt (i, 1);
        txtnm_pro.setText(nama_produk);
        String harga_jual = (String) tm.getValueAt (i, 2);
        txtharga_jual.setText(harga_jual);
        String harga_beli = (String) tm.getValueAt (i, 3);
        txtharga_beli.setText(harga_beli);
        String stok = (String) tm.getValueAt (i, 4);
        txtstok.setText(stok);
        String nama_satuan = (String) tm.getValueAt (i, 5);
        cbsat.setSelectedItem(nama_satuan);
        String nama_kategori = (String) tm.getValueAt (i, 6);
        cbkat.setSelectedItem(nama_kategori );
    }//GEN-LAST:event_tbl_dataproMouseClicked

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tm = new DefaultTableModel (null,
        new Object[] {"Kode Produk","Nama Produk","Harga Jual","Harga Beli","Stok","Satuan","Kategori"});
        tbl_datapro.setModel(tm);
        tm.getDataVector().removeAllElements();
        try
        {
            PreparedStatement s=con.prepareStatement("SELECT * from tbl_produk where nama_produk LIKE '%"+txtcari.getText().toString()+"%'");
            ResultSet r=s.executeQuery();
            while(r.next())
            {
                Object[]data={
                r.getString(1),
                r.getString(2),
                r.getString(3),
                r.getString(4),
                r.getString(5),
                r.getString(6),
                r.getString(7)
                };
                tm.addRow(data);
            }
            }
        catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n"+e+"\n\n");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Produk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbkat;
    private javax.swing.JComboBox<String> cbsat;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton save;
    private javax.swing.JTable tbl_datapro;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtharga_beli;
    private javax.swing.JTextField txtharga_jual;
    private javax.swing.JTextField txtkode_pro;
    private javax.swing.JTextField txtnm_pro;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
