/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi_kasir_nabila;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author RPL-PC
 */
public class Halaman_Utama extends javax.swing.JFrame {
    private String username;
    private String level;

    /**
     * Creates new form Halaman_Utama
     */
    public Halaman_Utama() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

     public void setUsername(String u) {
        username = u;
    }
    
     public void setLevel(String l) {
        level = l;
        Form_Pembayaran trans = new Form_Pembayaran();
        switch (level) {
            case "admin":
                transaksi.hide();
                break;
            case "kasir":
                dtmaster.hide();
                laporan.hide();
                transaksi.setText("Transaksi");
                out.setText("Logout");
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        dtmaster = new javax.swing.JMenu();
        jpengguna = new javax.swing.JMenuItem();
        jproduk = new javax.swing.JMenuItem();
        jsatuan = new javax.swing.JMenuItem();
        jkategori = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        jtrans = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        jstok = new javax.swing.JMenuItem();
        out = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/halut.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        dtmaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/report (1).png"))); // NOI18N
        dtmaster.setText("Master Data");
        dtmaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtmasterMouseClicked(evt);
            }
        });
        dtmaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtmasterActionPerformed(evt);
            }
        });

        jpengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-user-group-30.png"))); // NOI18N
        jpengguna.setText("Pengguna");
        jpengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpenggunaActionPerformed(evt);
            }
        });
        dtmaster.add(jpengguna);

        jproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-product-30.png"))); // NOI18N
        jproduk.setText("Produk");
        jproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprodukActionPerformed(evt);
            }
        });
        dtmaster.add(jproduk);

        jsatuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-unit-30.png"))); // NOI18N
        jsatuan.setText("Satuan");
        jsatuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsatuanMouseClicked(evt);
            }
        });
        jsatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsatuanActionPerformed(evt);
            }
        });
        dtmaster.add(jsatuan);

        jkategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-category-30.png"))); // NOI18N
        jkategori.setText("Kategori");
        jkategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jkategoriMouseClicked(evt);
            }
        });
        jkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkategoriActionPerformed(evt);
            }
        });
        dtmaster.add(jkategori);

        jMenuBar1.add(dtmaster);

        transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/card-payment.png"))); // NOI18N
        transaksi.setText("Transaksi");
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiMouseClicked(evt);
            }
        });

        jtrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-sale-30.png"))); // NOI18N
        jtrans.setText("Order");
        jtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtransActionPerformed(evt);
            }
        });
        transaksi.add(jtrans);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-money-30.png"))); // NOI18N
        jMenuItem1.setText("Pembayaran");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        transaksi.add(jMenuItem1);

        jMenuBar1.add(transaksi);

        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/report.png"))); // NOI18N
        laporan.setText("Laporan");
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });

        jstok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-stock-30.png"))); // NOI18N
        jstok.setText("Stok Barang");
        jstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstokActionPerformed(evt);
            }
        });
        laporan.add(jstok);

        jMenuBar1.add(laporan);

        out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/check-out.png"))); // NOI18N
        out.setText("Logout");
        out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outMouseClicked(evt);
            }
        });
        jMenuBar1.add(out);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpenggunaActionPerformed
        // TODO add your handling code here:
        Form_Pengguna hm=new Form_Pengguna();
        hm.show();
    }//GEN-LAST:event_jpenggunaActionPerformed

    private void outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outMouseClicked
        // TODO add your handling code here:
        int jawab;
        if((jawab = JOptionPane.showConfirmDialog(null, "Anda yakin ingin logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION)) == 0){
            Login lg = new Login();
            lg.show();
            this.dispose();
        }
        
    }//GEN-LAST:event_outMouseClicked

    private void dtmasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtmasterMouseClicked
         // TODO add your handling code here:
    }//GEN-LAST:event_dtmasterMouseClicked

    private void jprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprodukActionPerformed
        // TODO add your handling code here:
        Form_Produk hm=new Form_Produk();
        hm.show();
    }//GEN-LAST:event_jprodukActionPerformed

    private void transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseClicked
         // TODO add your handling code here:
    }//GEN-LAST:event_transaksiMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_laporanMouseClicked

    private void dtmasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtmasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtmasterActionPerformed

    private void jstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstokActionPerformed
        // TODO add your handling code here:
        Form_StokProduk hm=new Form_StokProduk();
        hm.show();
    }//GEN-LAST:event_jstokActionPerformed

    private void jkategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jkategoriMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jkategoriMouseClicked

    private void jsatuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsatuanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jsatuanMouseClicked

    private void jsatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsatuanActionPerformed
        // TODO add your handling code here:
        Form_Satuan hm=new Form_Satuan();
        hm.show();
    }//GEN-LAST:event_jsatuanActionPerformed

    private void jkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkategoriActionPerformed
        // TODO add your handling code here:
        Form_Kategori hm=new Form_Kategori();
        hm.show();
    }//GEN-LAST:event_jkategoriActionPerformed

    private void jtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtransActionPerformed
        // TODO add your handling code here:
        Form_Order hm=new Form_Order();
        hm.show();
    }//GEN-LAST:event_jtransActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:Form_Order hm=new Form_Order();
        Form_Pembayaran hm=new Form_Pembayaran();
        hm.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halaman_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halaman_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halaman_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halaman_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halaman_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu dtmaster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jkategori;
    private javax.swing.JMenuItem jpengguna;
    private javax.swing.JMenuItem jproduk;
    private javax.swing.JMenuItem jsatuan;
    private javax.swing.JMenuItem jstok;
    private javax.swing.JMenuItem jtrans;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenu out;
    private javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables
}
